# Generated by Django 4.2.5 on 2023-09-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
