# Generated by Django 4.2.5 on 2023-09-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion_app', '0003_alter_publicacion_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='comentario',
            new_name='detalle',
        ),
    ]
