# Generated by Django 4.2.5 on 2023-09-10 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion_app', '0004_rename_comentario_publicacion_detalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['fecha_creacion_publicacion']},
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_creacion_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
