# Generated by Django 4.2.5 on 2023-09-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion_app', '0004_rename_comentario_publicacion_detalle'),
        ('comentario_app', '0002_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publicacion_app.publicacion'),
        ),
    ]
