# Generated by Django 4.2.5 on 2023-09-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario_app', '0003_comentario_publicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion_comentario']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_creacion',
            new_name='fecha_creacion_comentario',
        ),
    ]
